### ISSUE TITLE
Amplify.DataStoreError error 8.

### ISSUE THREAD

**Issue by wgfilho** [aws-amplify/amplify-ios#1180]
**Describe the bug**
I have an app with 8 models and one of them with about 3500 entries. Whenever I do an initial sync, it syncs some models but don't sync others. What models are synced is random or fails is random, but very rarely all models are synced correctly.

For the ones that aren't, when I do a query I get:

Error on query() for type - The operation couldn’t be completed. (Amplify.DataStoreError error 8.)

Please, let me know what other info do you need.

Thanks!

**To Reproduce**
1. Do an initial sync of the app
2. Wait for the initial sync to finish
3. See error

**Expected behavior**
All models are synced

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.8.1
 - Dependency Manager: SPM
 - Swift Version: [e.g. 5.0]
 - CLI Version: 4.47.1
 - Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Device Information (please complete the following information):**
 - Device: iPhone 11 Pro Max, Simulator
 - iOS Version: 14.4
 - Specific to simulators:

**Additional context**

**Comment by anatomybook** [comment]
I've run into similar issues. For me the problem is that some models contain orphaned items, i.e. items where the parent has been erased, but the child is still there. Perhaps the same applies to you?! Is it always the same models, that don't sync? If so, you may want to check your DB.

**Comment by wgfilho** [comment]
I don't think it is a DB error because the models that end up returning this error are apparently random. From the 8 models that I have, I have seen from 0 to 4 models give the error. 

And all I have to do is remove the app, install/login again.

**Comment by anatomybook** [comment]
Ok. Then it looks to the case reported [here](https://github.com/aws-amplify/amplify-ios/issues/1001). However, this has been fixed and so far it's been working fine for me, i.e. I haven't had problems ever since. I also have some models with ~9000 items and other models with ~5000.

**Comment by wgfilho** [comment]
Yes, it definetely looks like it. Since the models that are gives the error are not the same, it probably is a race condition somewhere. 

I'll try to monitor the dataStore events to see if I can find more useful info.

**Comment by ruiguoamz** [comment]
Hi @wgfilho 

Are you still seeing the bug?

As @anatomybook mentioned, this foreign key constraints issue should be fixed and released.

**Comment by wgfilho** [comment]
Hi!

I don't think it's still happening. I don't know what changed.

[]'s
Walter

**Comment by ruiguoamz** [comment]
Glad to hear that it's not happening anymore. So I am closing this issue.

But feel free to reopen it if the bug happen again
